version: 1.3.{build}
image: Visual Studio 2015
build_script:
- ps: "Invoke-WebRequest 'https://github.com/x64dbg/x64dbg/releases/download/snapshot/snapshot_2019-08-23_00-59.zip'  -OutFile 'pluginsdk.zip'\ncmd /r rmdir /S /Q pluginsdk\ncmd /r 7z x pluginsdk.zip\ncmd /r dir\ncmd /r dir pluginsdk\n\nGet-Content 'commithash.txt'\n\ncmd /r dir C:\\Qt\ncmd /r dir C:\\Qt\\5.6\\\ncmd /r dir C:\\Qt\\5.6\\msvc2013_64\ncmd /r dir \"C:\\Program Files (x86)\\\"\n$Env:path += \";C:\\Qt\\5.6\\msvc2013_64\\bin\"\n\npushd 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC'    \ncmd /c \"vcvarsall.bat amd64&set\" |\nforeach {\n  if ($_ -match \"=\") {\n    $v = $_.split(\"=\"); set-item -force -path \"ENV:\\$($v[0])\"  -value \"$($v[1])\"\n  }\n}\npopd\nwrite-host \"`nVisual Studio 2013 Command Prompt variables set.\" -ForegroundColor Yellow\n\n\ncmd /r qmake quickaccess.pro\ncmd /r dir\ncmd /r nmake\ncmd /r dir"
artifacts:
- path: release/quickaccess.dp64
  name: release
deploy:
- provider: GitHub
  auth_token:
    secure: p+d6K6Jlo9DJXiqpFrwuK5rpXMQbkyIkj7w8jKVlEbE+vrszJL6X3ybLib+4u3Jn
